import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    const winopen = () => {
        window.open("http://localhost:3000/popup/partners/loreal/callback?status=success");
    }
    const winopenself = () => {
        alert('asdasd');
        window.open("http://localhost:3000/popup/partners/loreal/callback?status=success", "_self")
    }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <p>
              mybeautybox
              가입이 완료되었습니다.
          </p>
          <a href="http://localhost:3000/popup/partners/loreal/callback?status=success">
            확인(성공)
          </a>
          <a href="http://localhost:3000/popup/partners/loreal/callback?status=success" target="_self">
              확인(성공, _self)
          </a>
          <a href="http://localhost:3000/popup/partners/loreal/callback?status=success" target="_blank" rel="noreferrer">
              확인(성공, _black)
          </a>
          <button type="button" onClick={winopen}>
              확인(성공, window.open)
          </button>
          <button type="button" onClick={winopenself}>
              확인(성공, window.open, _self)
          </button>
          <a href="http://localhost:3000/popup/partners/loreal/callback">
            확인(실패)
          </a>
      </main>
    </>
  )
}
